version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  kubectl:
    image: bitnami/kubectl
    container_name: kubectl_proxy
    command: proxy --server https://minikube:8443 --address 0.0.0.0 --port 8001 --client-key /client.key --client-certificate /client.crt --insecure-skip-tls-verify
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - ~/.minikube/profiles/minikube/client.crt:/client.crt
      - ~/.minikube/profiles/minikube/client.key:/client.key
    networks:
      - minikube

volumes:
  pg_data:

networks:
  minikube:
    external: true
