apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    ingressClassName: "traefik"
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - secretName: letsdeploy-tls
      hosts:
        - letsdeploy.space
  rules:
    - host: letsdeploy.space
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
          - path: /v3
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
          - path: /swagger-ui.html
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http80
  selector:
    app: backend

---

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: letsdeploy
  name: letsdeploy-service-account
automountServiceAccountToken: true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: letsdeploy-cluster-role
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: letsdeploy-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: letsdeploy-cluster-role
subjects:
  - kind: ServiceAccount
    namespace: letsdeploy
    name: letsdeploy-service-account

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: letsdeploy-service-account
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend
          image: ghcr.io/kuzznya/letsdeploy/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: POSTGRES_HOST
              value: postgres:5432
            - name: POSTGRES_DATABASE
              value: postgres
            - name: POSTGRES_USERNAME
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: letsdeploy-secrets
                  key: POSTGRES_PASSWORD
            - name: KUBERNETES_IN_CLUSTER
              value: "true"
          livenessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 5
            terminationGracePeriodSeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
