postgres:
  host: localhost:5432
  username: postgres
  database: postgres
redis:
  host: localhost:6379
migrations:
  path: migrations
log:
  level: debug
tls:
  enabled: true
  cluster-issuer: letsencrypt-prod
oidc:
  provider: https://auth.kuzznya.com/realms/letsdeploy
  username-claim: preferred_username
